version: "3.2"

services:
  django:
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
    depends_on:
      - pgdb
      - redis

  pgdb:
      image: postgres
      container_name: pgdb
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 5435:5432
      volumes:
          - pgdata:/var/lib/postgresql/data/
  redis:
      image: "redis:alpine"

volumes:
  pgdata:






